// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package request_repository

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0xcc, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1,
	0x2b, 0x4a, 0x2d, 0xc8, 0x2f, 0xce, 0x2c, 0xc9, 0x2f, 0xaa, 0x94, 0xe2, 0x85, 0x89, 0x81, 0x95,
	0x48, 0x49, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0x79, 0x49, 0xa5, 0x69, 0xfa, 0xa9,
	0xb9, 0x05, 0x25, 0x95, 0x10, 0x49, 0xa3, 0x4b, 0x8c, 0x5c, 0x12, 0x41, 0x10, 0xe5, 0x41, 0x70,
	0x13, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x82, 0xb8, 0x78, 0x9d, 0x8b, 0x52, 0x13,
	0x4b, 0x52, 0xa1, 0x2a, 0x84, 0xd4, 0xf5, 0x30, 0xad, 0xd3, 0x43, 0x51, 0x12, 0x90, 0x58, 0x94,
	0x98, 0x5b, 0x2c, 0x25, 0xa6, 0x07, 0xb1, 0x54, 0x0f, 0x66, 0xa9, 0x9e, 0x2b, 0xc8, 0x52, 0x25,
	0x06, 0xa1, 0x24, 0x2e, 0x1e, 0x9f, 0x4c, 0x90, 0x65, 0x60, 0xe5, 0xc5, 0x42, 0x6a, 0xd8, 0x8c,
	0x44, 0x56, 0x01, 0x35, 0x51, 0x83, 0x90, 0xba, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54,
	0x25, 0x86, 0x24, 0x36, 0xb0, 0xad, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xd5, 0x37,
	0xca, 0x29, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RequestRepositoryServiceClient is the client API for RequestRepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RequestRepositoryServiceClient interface {
	CreateRequest(ctx context.Context, in *CreateRequestParams, opts ...grpc.CallOption) (*empty.Empty, error)
	ListRequests(ctx context.Context, in *ListRequestsParams, opts ...grpc.CallOption) (*ListRequestsResponse, error)
}

type requestRepositoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRequestRepositoryServiceClient(cc *grpc.ClientConn) RequestRepositoryServiceClient {
	return &requestRepositoryServiceClient{cc}
}

func (c *requestRepositoryServiceClient) CreateRequest(ctx context.Context, in *CreateRequestParams, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/request.repository.RequestRepositoryService/CreateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestRepositoryServiceClient) ListRequests(ctx context.Context, in *ListRequestsParams, opts ...grpc.CallOption) (*ListRequestsResponse, error) {
	out := new(ListRequestsResponse)
	err := c.cc.Invoke(ctx, "/request.repository.RequestRepositoryService/ListRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestRepositoryServiceServer is the server API for RequestRepositoryService service.
type RequestRepositoryServiceServer interface {
	CreateRequest(context.Context, *CreateRequestParams) (*empty.Empty, error)
	ListRequests(context.Context, *ListRequestsParams) (*ListRequestsResponse, error)
}

// UnimplementedRequestRepositoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRequestRepositoryServiceServer struct {
}

func (*UnimplementedRequestRepositoryServiceServer) CreateRequest(ctx context.Context, req *CreateRequestParams) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequest not implemented")
}
func (*UnimplementedRequestRepositoryServiceServer) ListRequests(ctx context.Context, req *ListRequestsParams) (*ListRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequests not implemented")
}

func RegisterRequestRepositoryServiceServer(s *grpc.Server, srv RequestRepositoryServiceServer) {
	s.RegisterService(&_RequestRepositoryService_serviceDesc, srv)
}

func _RequestRepositoryService_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRepositoryServiceServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/request.repository.RequestRepositoryService/CreateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRepositoryServiceServer).CreateRequest(ctx, req.(*CreateRequestParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestRepositoryService_ListRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRepositoryServiceServer).ListRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/request.repository.RequestRepositoryService/ListRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRepositoryServiceServer).ListRequests(ctx, req.(*ListRequestsParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _RequestRepositoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "request.repository.RequestRepositoryService",
	HandlerType: (*RequestRepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequest",
			Handler:    _RequestRepositoryService_CreateRequest_Handler,
		},
		{
			MethodName: "ListRequests",
			Handler:    _RequestRepositoryService_ListRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
